repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        files: \.py$
      - id: end-of-file-fixer
        name: end-of-file-fixer
        files: \.py$
      - id: double-quote-string-fixer
        name: double-quote-string-fixer
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.5.1
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print
          - flake8-implicit-str-concat
  - repo: https://github.com/mondeja/pre-commit-hooks
    rev: v1.8.0
    hooks:
      - id: root-editorconfig-required
      - id: dev-extras-required
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --filter-files
        files: \.py$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: .+\.(yml|yaml)
        args:
          - -c
          - .yamllint
  - repo: https://github.com/mondeja/pre-commit-po-hooks
    rev: v1.7.3
    hooks:
      - id: obsolete-messages
      - id: untranslated-messages
      - id: remove-metadata
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.2
    hooks:
      - id: editorconfig-checker
