site_name: http-request-codegen
site_url: https://github.com/mondeja/http-request-codegen
site_description: Multilanguage HTTP request code snippet generator.
site_author: Álvaro Mondéjar Rubio

repo_url: https://github.com/mondeja/http-request-codegen
repo_name: http-request-codegen
edit_uri: ''
copyright: Copyright &copy; 2020 Álvaro Mondéjar

docs_dir: docs
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

nav:
  - Description: index.md
  - Setup:
    - Installation: install.md
  - Demo:
    - Available generators: demo.md
  - Support:
    - Supported features: support.md

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: True
  - meta

plugins:
  - search
  - macros:
      module_name: docs_macros
  - minify:
      minify_html: true
      minify_js: true
