site_name: http-request-codegen
site_url: https://mondeja.github.io/http-request-codegen/
site_description: Multilanguage HTTP request code snippet generator.
site_author: Álvaro Mondéjar Rubio

repo_url: https://github.com/mondeja/http-request-codegen
repo_name: http-request-codegen
edit_uri: tree/master/docs
copyright: Copyright &copy; 2020-2024 Álvaro Mondéjar

docs_dir: docs
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github

extra:
  alternate:
    - name: English
      lang: en
    - name: Español
      link: es
      lang: es

nav:
  - Introduction: index.md
  - Reference: reference.md
  - Development: dev.md

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details

plugins:
  - search:
      lang: en
  - include-markdown
  - macros:
      module_name: docs_macros
  - minify:
      minify_html: true
      minify_js: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - ./http-request-codegen
          options:
            show_source: false
            show_root_toc_entry: false
  - exclude:
      glob:
        - '*.py'
        - '*.pyc'
  - mdpo
