site_name: http-request-codegen
site_url: https://github.com/mondeja/http-request-codegen
site_description: Multilanguage HTTP request code snippet generator.
site_author: Álvaro Mondéjar Rubio

repo_url: https://github.com/mondeja/http-request-codegen
repo_name: http-request-codegen
edit_uri: tree/master/docs
copyright: Copyright &copy; -20212020 Álvaro Mondéjar

docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

nav:
  - Introduction: index.md
  - Reference: reference.md
  - Development: dev.md

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: True
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - include-markdown
  - macros:
      module_name: docs_macros
  - minify:
      minify_html: true
      minify_js: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_root_toc_entry: false
      watch:
      - http_request_codegen
  - exclude:
      glob:
        - '*.py'
        - '*.pyc'
