name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip coveralls
          python -m pip install .[test]
          pip list
      - name: Test with pytest
        # https://github.com/actions/runner/issues/241#issuecomment-577360161
        run: |
          pytest -svv --cov=http_request_codegen --cov-config setup.cfg
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-sdist:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: test
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python v3.8
        with:
          python-version: 3.8
      - name: Build sdist
        run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build-wheel:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: test
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python v3.8
        with:
          python-version: 3.8
      - name: Install wheel
        run: python -m pip install --upgrade wheel
      - name: Build wheel
        run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  pypi-upload:
    name: Upload to PyPI
    needs:
      - build-sdist
      - build-wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          # repository_url: https://test.pypi.org/legacy/
          skip_existing: true
