name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Documentation build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .[doc]
          pip list
      - name: Show documentation configuration
        run: cat mkdocs.yml
      - name: Test documentation build
        run: python -m mkdocs build --verbose
      - name: Show tree
        run: tree site
